### ISSUE TITLE
Can enter multiple operators

### ISSUE THREAD

**Issue by mv805** [Uaitt/calculator#2]
The user can enter multiple succesive operators such as 'xxxxxx' and '+++++'. Expected behavior would be you should only be able to enter one at a time after each number.

**Comment by Uaitt** [comment]
You are right, I did not think about this.

This should be manageable with adding an if condition on the operator functions that let's you add an operator on the screen only if the flag "LastDigitIsNumber" is true. Will fix this later.

**Comment by Uaitt** [comment]
Issue fixed
